version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  agid:
    image: wazoplatform/wazo-agid-tests
    ports:
      - "4573"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "../..:/usr/src/wazo-agid"
      - "./etc/wazo-agid/conf.d/50-default.yml:/etc/wazo-agid/conf.d/50-default.yml"
      - "./etc/xivo/asterisk/xivo_in_callerid.conf:/etc/xivo/asterisk/xivo_in_callerid.conf"
      - "./etc/xivo/asterisk/xivo_ring.conf:/etc/xivo/asterisk/xivo_ring.conf"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/opt/venv/lib/python2.7/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python2.7/site-packages/xivo"

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - '9497'

  postgres:
    image: wazoplatform/wazo-confd-db-test:local
    ports:
      - "5432"
